source "https://rubygems.org"
gem 'calabash-android'
gem 'cucumber'
source "https://rubygems.org"
gem 'calabash-android'
gem 'cucumber'
source "https://rubygems.org"
gem 'calabash-android'
gem 'cucumber'
source "https://rubygems.org"
gem 'calabash-android'
gem 'cucumber'
source "https://rubygems.org"
gem 'calabash-android'
gem 'cucumber'
source "https://rubygems.org"
gem 'calabash-android'
gem 'cucumber'
source "https://rubygems.org"
gem 'calabash-android'
gem 'cucumber'
source "https://rubygems.org"
gem 'calabash-android'
gem 'cucumber'
source "https://rubygems.org"
gem 'calabash-android'
gem 'cucumber'
source "https://rubygems.org"
gem 'calabash-android'
gem 'cucumber'
